### PR TITLE
Feature: Bootstrap projects

### LINKED ISSUE #2: Set up a repository

### LINKED ISSUE #3: Set up backend project (express)

### LINKED ISSUE #4: Set up frontend (plain)

### LINKED ISSUE #5: Set up database connection with Mongo and Mongoose

### PR DESCRIPTION
**Pull request by Roman-Octavian**
closes #2, closes #3, closes #4, closes #5

> [!IMPORTANT]  
> Get `.env` on discord and place in `server`

## Testing:

```bash
git clone https://github.com/Roman-Octavian/travel-destinations
```
```bash
cd travel-destinations/
```
```bash
git checkout feature/bootstrap-projects
```
```bash
npm i
```
```bash
# Copy .env over from discord into the server directory
```
```bash
npm run dev
```

See [README](https://github.com/Roman-Octavian/travel-destinations/blob/95ae6c83d40929d9a5beab360dd1c68ec04487f8/README.md) for more

### CODE REVIEW

**Review by simonakardel — APPROVED** [review]

**Comment by Roman-Octavian** [comment]
@simonakardel can you run this with `npm run dev` and both:

http://localhost:3000

and 

http://localhost:8080/api/v1/destinations

work?

**Comment by simonakardel** [comment]
> @simonakardel can you run this with `npm run dev` and both:
> 
> http://localhost:3000
> 
> and
> 
> http://localhost:8080/api/v1/destinations
> 
> work?

hmm http://localhost:8080/api/v1/destinations doesn't work

**Comment by Roman-Octavian** [comment]
> > @simonakardel can you run this with `npm run dev` and both:
> > http://localhost:3000
> > and
> > http://localhost:8080/api/v1/destinations
> > work?
> 
> hmm http://localhost:8080/api/v1/destinations doesn't work

@simonakardel My bad, try:

http://localhost:8080/api/v1/destination

**Comment by simonakardel** [comment]
> > > @simonakardel can you run this with `npm run dev` and both:
> > > http://localhost:3000
> > > and
> > > http://localhost:8080/api/v1/destinations
> > > work?
> > 
> > 
> > hmm http://localhost:8080/api/v1/destinations doesn't work
> 
> @simonakardel My bad, try:
> 
> http://localhost:8080/api/v1/destination

works

**Review by nikidkny — APPROVED** [review]

**Pull request merged**
